#!/bin/bash
set -e

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'
CYAN=$'\033[0;36m'
NC=$'\033[0m' # No Color

# Check if we're in the right directory
if [ ! -f "pyproject.toml" ] && [ ! -f "package.json" ]; then
    echo "${RED}Error: Please run this script from the Artemis City root directory.${NC}"
    exit 1
fi

# Function to generate secure random key
generate_key() {
    if command -v openssl &> /dev/null; then
        openssl rand -hex 32
    elif command -v python3 &> /dev/null; then
        python3 -c "import secrets; print(secrets.token_hex(32))"
    elif command -v python &> /dev/null; then
        python -c "import secrets; print(secrets.token_hex(32))"
    elif command -v node &> /dev/null; then
        node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
    else
        echo "${RED}Error: No suitable tool found to generate secure keys.${NC}"
        echo "Please install openssl, python, or node."
        exit 1
    fi
}

# Check for existing .env files
check_existing() {
    local file=$1
    if [ -f "$file" ]; then
        echo "${YELLOW}Warning: $file already exists.${NC}"
        read -p "Overwrite? (y/N): " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo "Skipping $file"
            return 1
        fi
    fi
    return 0
}

echo "${CYAN}Step 1: Generating secure API keys...${NC}"
echo ""

MCP_API_KEY=$(generate_key)
echo "${GREEN}✓ MCP API Key generated${NC}"

OBSIDIAN_API_KEY_PLACEHOLDER="your_obsidian_api_key_here"

echo ""
echo "${CYAN}Step 2: Creating root .env file...${NC}"

if check_existing ".env"; then
    cat > .env << EOF
# ============================================
# ARTEMIS CITY - ENVIRONMENT CONFIGURATION
# ============================================
# Generated by setup_secrets.sh on $(date)
# NEVER commit this file to version control!

# ============================================
# MCP SERVER CONFIGURATION
# ============================================

# MCP Server base URL
MCP_BASE_URL=http://localhost:3000

# MCP API Key for authentication (auto-generated)
MCP_API_KEY=${MCP_API_KEY}

# ============================================
# OBSIDIAN CONFIGURATION
# ============================================

# Obsidian Local REST API base URL
OBSIDIAN_BASE_URL=http://localhost:27124

# Obsidian Local REST API Key
# Get this from Obsidian -> Settings -> Local REST API -> Copy API Key
OBSIDIAN_API_KEY=${OBSIDIAN_API_KEY_PLACEHOLDER}

# ============================================
# OPTIONAL CONFIGURATION
# ============================================

# MCP Server Port
PORT=3000

# Log Level: DEBUG, INFO, WARN, ERROR
MCP_LOG_LEVEL=INFO
EOF

    chmod 600 .env
    echo "${GREEN}✓ Root .env created with secure permissions (600)${NC}"
fi

echo ""
echo "${CYAN}Step 3: Creating Memory Layer .env file...${NC}"

# Check for Memory Layer directory (various possible names)
MEMORY_LAYER_DIR=""
if [ -d "app/Artemis Agentic Memory Layer" ]; then
    MEMORY_LAYER_DIR="app/Artemis Agentic Memory Layer"
elif [ -d "Artemis Agentic Memory Layer" ]; then
    MEMORY_LAYER_DIR="Artemis Agentic Memory Layer"
elif [ -d "app" ]; then
    MEMORY_LAYER_DIR="app"
fi

if [ -n "$MEMORY_LAYER_DIR" ]; then
    ENV_FILE="$MEMORY_LAYER_DIR/.env"
    if check_existing "$ENV_FILE"; then
        cat > "$ENV_FILE" << EOF
# ============================================
# ARTEMIS MEMORY LAYER - ENVIRONMENT
# ============================================
# Generated by setup_secrets.sh on $(date)
# NEVER commit this file to version control!

# MCP API Key (must match root .env)
MCP_API_KEY=${MCP_API_KEY}

# Server Port
PORT=3000

# Obsidian Local REST API
OBSIDIAN_BASE_URL=http://localhost:27124
OBSIDIAN_API_KEY=${OBSIDIAN_API_KEY_PLACEHOLDER}
EOF

        chmod 600 "$ENV_FILE"
        echo "${GREEN}✓ Memory Layer .env created at: $ENV_FILE${NC}"
    fi
else
    echo "${YELLOW}⚠ Memory Layer directory not found. Skipping.${NC}"
fi

echo ""
echo "${CYAN}Step 4: Verifying .gitignore protection...${NC}"

# Ensure .env files are in .gitignore
if [ -f ".gitignore" ]; then
    if ! grep -q "^\.env$" .gitignore; then
        echo "" >> .gitignore
        echo "# Environment files (auto-added by setup_secrets.sh)" >> .gitignore
        echo ".env" >> .gitignore
        echo ".env.local" >> .gitignore
        echo ".env.*.local" >> .gitignore
        echo "${GREEN}✓ Added .env patterns to .gitignore${NC}"
    else
        echo "${GREEN}✓ .env already protected in .gitignore${NC}"
    fi
else
    echo "${YELLOW}⚠ No .gitignore found. Please ensure .env files are ignored.${NC}"
fi

echo ""
echo "${BLUE}============================================${NC}"
echo "${GREEN}  ✓ SETUP COMPLETE!${NC}"
echo "${BLUE}============================================${NC}"
echo ""
echo "${CYAN}Next Steps:${NC}"
echo ""
echo "1. ${YELLOW}Configure Obsidian API Key:${NC}"
echo "   - Open Obsidian"
echo "   - Go to Settings -> Community Plugins -> Local REST API"
echo "   - Copy your API key"
echo "   - Paste it into .env (replace '${OBSIDIAN_API_KEY_PLACEHOLDER}')"
echo ""
echo "2. ${YELLOW}Start the MCP Server:${NC}"
echo "   cd \"$MEMORY_LAYER_DIR\" && npm run dev"
echo ""
echo "3. ${YELLOW}Verify the setup:${NC}"
echo "   curl http://localhost:3000/health"
echo ""
echo "${RED}SECURITY REMINDER:${NC}"
echo "  - NEVER commit .env files to git"
echo "  - NEVER share your API keys"
echo "  - Rotate keys if they are ever exposed"
echo ""
