%% Zoottelkeeper: Beginning of the autogenerated index file list  %%
📄 [[Artemis-City/Agents_MD/The_Pack_Rat/(2)._Reflection]]
📄 [[Artemis-City/Agents_MD/The_Pack_Rat/Agent_Card.md.md]]
📄 [[Artemis-City/Agents_MD/The_Pack_Rat/index.md.md]]
📄 [[Artemis-City/Agents_MD/The_Pack_Rat/Memory_Index.csv.md]]
📄 [[Artemis-City/Agents_MD/The_Pack_Rat/The_Pack_Rat.md]]
🗂️ [[Artemis-City/Agents_MD/The_Pack_Rat/Reflection/_Index_of_Reflection.md]]
%% Zoottelkeeper: End of the autogenerated index file list  %%
